### ISSUE TITLE
Tweepy is behind a version on conda-forge

### ISSUE THREAD

**Issue by lwasser** [conda-forge/tweepy-feedstock#6]
Issue:

If you notice - tweepy [is at version 3.7](https://github.com/tweepy/tweepy)  on pypi which supports python 3.7. However on conda-forge is at version 3.6 which is causing errors in our environment that is installing `python 3.7`. I see that #4 has a rebuild associated with it but it's failing and thus hasn't been merged. Is this something that can be fixed so we can use tweepy in our conda environment via conda-forge. THe fix for me was to update our environment to install tweepy from pip. However i do like to try to minimize channel mixing where i can.

<br/>
Environment (<code>conda list</code>):
Here is the PR with the environment changes that i had to make to ensure tweepy installed correctly:
https://github.com/earthlab/earth-analytics-python-env/pull/46 

and here is the error i was getting when the install instructions were for conda-forge (switched to pip in the PR above temporarily)

```
SpecsConfigurationConflictError: Requested specs conflict with configured specs.
requested specs:
- geocoder
- tweepy
pinned specs:
- python=3.7
```

@ocefpaf there is no rush on this item as it does seem to work now via pip but i wanted to call attention to the version mismatch here. @Harmon758 i noticed you've been working on tweepy (yay!) so perhaps this is something you can help with too? i'm happy to see the repo is active again.

<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Looks like PR #5 was merged but the package was not built. I'm firing up the CIs to check.

**Comment by ocefpaf** [comment]
The package was uploaded, https://anaconda.org/conda-forge/tweepy/files, and should be available in ~20 min.

**Comment by lwasser** [comment]
thank you @ocefpaf !! the build runs perfectly from conda-forge now with python 3.7
